using UnityEngine;

/*
 * I kid you not, this was generated by Microsoft Copilot.
 * I meddled with it a bit, because some things were off.
 * However, I don't know why this shows up in ALL the cameras.
 */


[RequireComponent(typeof(MeshFilter), typeof(MeshRenderer))]
public class SilverAnnulus : MonoBehaviour
{
    
    int segments = 100;

    /*
     * This is just for a demo, so it's quick and dirty.
     * But, you can use your own mesh, own shaders, etc.
     * 
     * These are updated in each frame, depending on what we do.
     * 
     * Tunnel vision:
     *  -innerRadius: 0.15f
     *  -outerRadius: 15.0f
     *  
     * Central scotoma
     *  -innerRadius: 0.0f
     *  -outerRadius: 0.2f
     *  
     * No deficit:
     *  -innerRadius: 10f;
     *  -outerRadius: 30f;
     */

    float innerRadius = 10f;
    float outerRadius = 50f;

    int current_visual_deficit_type = 0;

    MeshFilter meshFilter;
    MeshRenderer meshRenderer;

    void Start()
    {
        meshFilter = GetComponent<MeshFilter>();
        meshFilter.mesh = CreateAnnulusMesh();
        
        meshRenderer = GetComponent<MeshRenderer>();
        // I disabled this stuff, material is managed with a fixed material in the assets.
        //meshRenderer.material = new Material(Shader.Find("Standard"));
        //meshRenderer.material.color = Color.gray; // Silver color
    }



    void Update()
    {
        // we compare the local variable here with the modeSetter script loaded to a different GameObject
        if(current_visual_deficit_type != modeSetter.visual_deficit_type)
        {
            current_visual_deficit_type = modeSetter.visual_deficit_type; // Update the variable

            Debug.Log(string.Format("Switching to visual deficit type {0}\n", current_visual_deficit_type));

            // ASCII 0, 1, 2...
            switch(current_visual_deficit_type)
            {
                case 48:
                    // Normal vision
                    innerRadius = 10f;
                    outerRadius = 11f;
                    break;
                case 49:
                    // Central scotoma
                    innerRadius = 0.0f;
                    outerRadius = 0.25f;
                    break;

                case 50:
                    // Tunnel vision
                    innerRadius = 0.15f;
                    outerRadius = 15.0f;
                    break;

                default:
                    // Default is normal vision.
                    innerRadius = 10f;
                    outerRadius = 50f;
                    break;
            }

            Debug.Log(string.Format("Switching visual deficit dimensions to: {0}, {1}\n", innerRadius, outerRadius));
            // Update the mesh.
            meshFilter = GetComponent<MeshFilter>();
            meshFilter.mesh = null; // Delete the existing mesh.
            meshFilter.mesh = CreateAnnulusMesh(); // Create a msh with the updated dimensions.
            meshRenderer = GetComponent<MeshRenderer>();

        }


    }


    Mesh CreateAnnulusMesh()
    {
        Mesh mesh = new Mesh();
        Vector3[] vertices = new Vector3[segments * 2];
        int[] triangles = new int[segments * 6];

        float angleStep = 2 * Mathf.PI / segments;
        for (int i = 0; i < segments; i++)
        {
            float angle = i * angleStep;
            // Moved it so the center of the annulus would be 0, 0, 0
            float xInner = Mathf.Cos(angle) * innerRadius;
            float yInner = Mathf.Sin(angle) * innerRadius;
            float xOuter = Mathf.Cos(angle) * outerRadius;
            float yOuter = Mathf.Sin(angle) * outerRadius;

            vertices[i * 2] = new Vector3(xInner, 0, yInner);
            vertices[i * 2 + 1] = new Vector3(xOuter, 0, yOuter);

            int nextIndex = (i + 1) % segments;
            triangles[i * 6] = i * 2;
            triangles[i * 6 + 1] = nextIndex * 2;
            triangles[i * 6 + 2] = i * 2 + 1;

            triangles[i * 6 + 3] = nextIndex * 2;
            triangles[i * 6 + 4] = nextIndex * 2 + 1;
            triangles[i * 6 + 5] = i * 2 + 1;
        }

        mesh.vertices = vertices;
        mesh.triangles = triangles;
        mesh.RecalculateNormals();

        return mesh;
    }
}